# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Install prerequesites
        run: |
          sudo apt-get update
          sudo apt-get -y install rsync kmod execstack sqlite3 libsqlite3-dev libzstd-dev:i386 libzstd-dev cmake lib32z1-dev unar inkscape imagemagick subversion git bc \
            wget sudo ccache gcc g++ binutils autoconf automake autopoint libtool-bin make bzip2 libncurses5-dev libreadline-dev zlib1g-dev flex bison patch texinfo \
            tofrodos gettext pkg-config ecj fastjar perl libstring-crc32-perl ruby gawk python libusb-dev unzip intltool libacl1-dev libcap-dev libc6-dev-i386 \
            lib32ncurses5-dev gcc-multilib lib32stdc++6 libglib2.0-dev sqlite3:i386
          echo apt-get installed with return code: $?
            
      - name: make olddefconfig
        run: make olddefconfig
        
      - name: make
        run: make
        
      - name: sha1sum images/latest.image
        run: sha1sum images/latest.image > images/latest.image.sha1sum
        
      - uses: actions/upload-artifact@v1
        with:
          name: latest.image
          path: images/latest.image

      - uses: actions/upload-artifact@v1
        with:
          name: latest.image.sha1sum
          path: images/latest.image.sha1sum
